version: "3.8"

services:
  wordpress:
    container_name: ${CONTAINER_NAME}-wp
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./wp-data:/var/www/html
    restart: always

  db:
    container_name: ${CONTAINER_NAME}-db
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
